/*  ========================================================================  *\
    F I R S T  C O N T E N T -  S T I L U S  E S  F U N K C I O K
\*  ========================================================================  */

document.getElementById('firstContent').style.width = "100%";           // A tartalom szelessege...
document.getElementById('firstContent').style.height = "100%";          // A tartalom magassaga...
document.getElementById('firstContent').style.margin = "0 auto";        // A tartalom margojanak beallitasa...
document.getElementById('firstContent').style.padding = "0 auto";       // A tartalom paddingjanak beallitasa...
document.getElementById('firstContent').style.overflow = 'scroll';      // A tartalom scroll-olhato...
document.getElementById('firstContent').style.scrollbarWidth = 'none';  // A scrollbar eltuntetese...


/*  ========================================================================  *\
    E L S O   O L D A L - T A R T A L O M   B E T O L T E S E
\*  ========================================================================  */

// Az elso oldal betoltese a : 'greeting.html' tartalommal...
document.addEventListener('DOMContentLoaded', function () {  // Az oldal betoltese utan...
    firstContent('pages/greeting.html');                     // Az oldal tartalmanak a betoltese...
});

    // Az oldal tartalmanak betoltese...
    function firstContent(url) {  // Az oldal tartalmanak URL-je...
        fetch(url)                // Az oldal tartalmanak URL-je...
            // A valasz ellenorzese...
            .then(response => {
                if (!response.ok) {                                                    // Ha a valasz nem OK...
                    throw new Error('<h4>Error code : ' + response.status + '</h4>');  // Hiba uzenet...
                }
                // A valasz szoveg atalakitasa...
                return response.text();
            })
            // Az oldal tartalmanak beallitasa...
            .then(data => {                                                // A valasz tartalmanak beallitasa...
                document.getElementById('firstContent').innerHTML = data;  // Az oldal tartalmanak beallitasa...
            })
            // A hiba uzenet beallitasa...
            .catch(error => {                                                                                          // Hiba eseten...
                document.getElementById('firstContent').innerHTML = '<h2>ERROR</h2><h4>' + error.message + ' !</h4>';  // Hiba uzenet...
            })
    }


/*  ========================================================================  *\
    M E N U  C O N T E N T  -  S T I L U S  E S  F U N K C I O K
\*  ========================================================================  */

document.getElementById('menuContent').style.width = "100%";             // A menu szelessege...
document.getElementById('menuContent').style.height = "0%";              // A menu magassaga...
document.getElementById('menuContent').style.overflow = 'hidden';        // A menu scroll-olhato...
document.getElementById('menuContent').style.scrollbarWidth = 'none';    // A scrollbar eltuntetese...

    function openNav() {
        document.getElementById('menuContent').style.width = "100%";     // A menu megnyitasa...
        document.getElementById('menuContent').style.height = "100%";    // A menu megnyitasa...
        document.getElementById('menuContent').style.transition = '1s';  // A menu megnyitasa animacioval...
    }

    function closeNav() {
        document.getElementById('menuContent').style.width = "100%";     // A menu bezarasa...
        document.getElementById('menuContent').style.height = "0%";      // A menu bezarasa...
        document.getElementById('menuContent').style.transition = '1s';  // A menu bezarasa animacioval...
    }

/*  ========================================================================  *\
    O L D A L T A R T A L M A K -  B E T O L T E S E
\*  ========================================================================  */

function loadContent(menuContent) { 
 
    document.getElementById("menuContent").style.height = "0%";      // A menu bezarasa...
    document.getElementById('menuContent').style.transition = '1s';  // A menu bezarasa animacioval...

    fetch(menuContent)  // Az oldal tartalmanak URL-je...
        // A valasz ellenorzese...
        .then(response => {
            if (!response.ok) {                                                    // Ha a valasz nem OK...
                throw new Error('<h4>Error code : ' + response.status + '</h4>');  // Hiba uzenet...
            }
            // A valasz szoveg atalakitasa...
            return response.text();
        })
        // A valasz tartalmanak beallitasa...
        .then(data => {                                                // A valasz tartalmanak beallitasa...
            document.getElementById('firstContent').innerHTML = data;  // A tartalom beállítása...
        })
        // Hiba eseten...
        .catch(error => {
            document.getElementById('firstContent').innerHTML = '<h2>ERROR</h2><h4>' + error.message + ' !</h4>';  // Hiba uzenet...
        })
}